---

- name: Add ppa key
  sudo: yes
  apt_key: id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags: postgresql

- name: Add ppa
  sudo: yes
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
  tags: postgresql

- name: Install
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - postgresql-{{pg_version}}
    - libpq-dev
    - postgresql-contrib-{{pg_version}}
    - python-psycopg2
  notify:
    - Restart service
  tags: postgresql

- name: Install postgis
  sudo: yes
  apt: name=postgresql-{{pg_version}}-postgis-2.1 state=latest
  when: postgis

- name: Install configs
  sudo: yes
  copy: src={{item}} dest=/etc/postgresql/{{pg_version}}/main/ owner=postgres group=postgres mode=0640
  with_items:
    - pg_hba.conf
    - "{{pg_version}}/postgresql.conf"
  notify:
    - Restart service
  tags: postgresql

- name: Add vagrant role
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=vagrant role_attr_flags="SUPERUSER"
  tags: postgresql
