---

- name: Install keychain
  become: yes
  apt: name=keychain state=latest
  tags: keychain

- name: Load keychain
  lineinfile: dest=.bashrc line='eval `keychain --eval --agents gpg`'
  tags: keychain
