---

#Build Phantomjs
- name: Phantomjs prereqs
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - build-essential
    - g++
    - flex
    - bison
    - gperf
    - ruby
    - perl
    - libsqlite3-dev
    - libfontconfig1-dev
    - libicu-dev
    - libfreetype6
    - libssl-dev
    - libpng-dev
    - libjpeg-dev
    - ttf-mscorefonts-installer
  tags:
    - build-phantomjs2

# A fork of phantom that fixes file upload issues. Should be fixed in 2.0.1
- name: Clone phantomjs repo
  git: repo=https://github.com/stevepm/phantomjs.git dest=phantomjs/ accept_hostkey=yes
  tags:
    - build-phantomjs2

- name: Build phantomjs
  shell: "git checkout 5f663b8b39138c0510a7 && ./build.sh --confirm --silent --jobs {{ansible_processor_cores}}"
  args:
    chdir: ~/phantomjs
    creates: ~/phantomjs/bin/phantomjs
  tags:
    - build-phantomjs2

- name: Install phantomjs
  shell: "sudo install ~/phantomjs/bin/phantomjs /usr/local/bin/"
  args:
    creates: /usr/local/bin/phantomjs
  tags:
    - build-phantomjs2

- name: Package phantomjs
  shell: "cp ~/phantomjs/bin/phantomjs /vagrant && xz --stdout -9e ~/phantomjs/bin/phantomjs > /vagrant/phantomjs-{{ansible_distribution_version}}-amd64.xz"
  args:
    creates: /vagrant/phantomjs-{{ansible_distribution_version}}-amd64.xz
  tags:
    - build-phantomjs2

# Install pre-built phantom
- name: Download
  get_url:
    url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-i686.tar.bz2
    dest: /tmp/phantomjs-2.1.1-linux-i686.tar.bz2
  tags: phantomjs2

- name: Uncompress
  become: yes
  command: tar -xf /tmp/phantomjs-2.1.1-linux-i686.tar.bz2 --strip 2 phantomjs-2.1.1-linux-i686/bin/phantomjs
  args:
    chdir: /usr/local/bin
    creates: /usr/local/bin/phantomjs
  tags: phantomjs2

- name: Set permissions
  become: yes
  file:
    group: root
    mode: 0755
    path: /usr/local/bin/phantomjs
    owner: root
  tags: phantomjs2

- name: Install phantom required libs
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - libsqlite3-dev
    - libfontconfig1-dev
    - libicu-dev
    - libfreetype6
    - libssl-dev
    - libpng-dev
    - libjpeg-dev
    - ttf-mscorefonts-installer
  tags: phantomjs2
