---

#Build Phantomjs
- name: Phantomjs prereqs
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - build-essential
    - g++
    - flex
    - bison
    - gperf
    - ruby
    - perl
    - libsqlite3-dev
    - libfontconfig1-dev
    - libicu-dev
    - libfreetype6
    - libssl-dev
    - libpng-dev
    - libjpeg-dev
    - ttf-mscorefonts-installer
  tags:
    - build-phantomjs2

- name: Clone phantomjs repo
  git: repo=git://github.com/ariya/phantomjs.git dest=phantomjs/
  tags:
    - build-phantomjs2


- name: Build phantomjs
  shell: "git checkout 2.0 && ./build.sh --confirm --silent --jobs {{ansible_processor_cores}}"
  args:
    chdir: ~/phantomjs
    creates: ~/phantomjs/bin/phantomjs
  tags:
    - build-phantomjs2

- name: Install phantomjs
  shell: "sudo install phantomjs /usr/local/bin/"
  args:
    chdir: ~/phantomjs
    creates: /usr/local/bin/phantomjs
  tags:
    - build-phantomjs2

# Install pre-built phantom
- name: Download pre-built phantomjs
  get_url: url=https://github.com/scottjacobsen/phantomjs/releases/download/2.0.0/phantomjs.xz dest=~/phantomjs.xz mode=0644
  tags: phantomjs2

- name: Install pre-built phantomjs
  shell: "unxz --keep phantomjs.xz && sudo install phantomjs /usr/local/bin && rm phantomjs"
  args:
    creates: /usr/local/bin/phantomjs
  tags: phantomjs2

- name: Install phantom required libs
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - libsqlite3-dev
    - libfontconfig1-dev
    - libicu-dev
    - libfreetype6
    - libssl-dev
    - libpng-dev
    - libjpeg-dev
    - ttf-mscorefonts-installer
  tags: phantomjs2
