---

- name: Download
  get_url:
    url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-i686.tar.bz2
    dest: /tmp/phantomjs-2.1.1-linux-i686.tar.bz2
  tags: phantomjs2

- name: Uncompress
  become: yes
  command: tar -xf /tmp/phantomjs-2.1.1-linux-i686.tar.bz2 --strip 2 phantomjs-2.1.1-linux-i686/bin/phantomjs
  args:
    chdir: /usr/local/bin
    creates: /usr/local/bin/phantomjs
  tags: phantomjs2

- name: Set permissions
  become: yes
  file:
    group: root
    mode: 0755
    path: /usr/local/bin/phantomjs
    owner: root
  tags: phantomjs2

- name: Install phantom required libs
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - libsqlite3-dev
    - libfontconfig1-dev
    - libicu-dev
    - libfreetype6
    - libssl-dev
    - libpng-dev
    - libjpeg-dev
    - ttf-mscorefonts-installer
  tags: phantomjs2
