---

# RCM dotfile manager

- name: Add ppa key
  become: yes
  apt_key: keyserver=keyserver.ubuntu.com id=4E9A5EF6BD18E32A513B691C4609D1E5ECA538E6
  tags: rcm

- name: Add ppa
  become: yes
  apt_repository: repo="deb http://ppa.launchpad.net/martin-frost/thoughtbot-rcm/ubuntu xenial main"
  tags: rcm

- name: Install
  become: yes
  apt: name=rcm
  tags: rcm
