---
- name: Install
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - curl
    - emacs24-nox
    - entr
    - git
    - httpie
    - tmux
    - units
    - zsh
    - silversearcher-ag

  tags: utils
